DROP TABLE IF EXISTS Tab_Teste;
CREATE TABLE Tab_Teste (
	col1 INT NOT NULL PRIMARY KEY,
	col2 INT NOT NULL);
SELECT * FROM Tab_Teste;

START TRANSACTION ;
INSERT Tab_Teste VALUES (1,111) ;
INSERT Tab_Teste VALUES (2,222) ;
COMMIT;
SELECT * FROM Tab_Teste;

START TRANSACTION ;
INSERT Tab_Teste VALUES (3,333) ;
INSERT Tab_Teste VALUES (4,444) ;
ROLLBACK;
SELECT * FROM Tab_Teste;
