DROP TABLE IF EXISTS Tab_Teste;
CREATE TABLE Tab_Teste (
col1 INT NOT NULL PRIMARY KEY,
col2 INT NOT NULL);
SELECT * FROM Tab_Teste;

DROP PROCEDURE IF EXISTS tratErroTransact;
DELIMITER $$
CREATE PROCEDURE tratErroTransact()
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		RESIGNAL;
	END;
	START TRANSACTION;
		INSERT Tab_Teste VALUES (1,111) ;
		INSERT Tab_Teste VALUES (2,222) ;
		INSERT Tab_Teste VALUES (3,'um') ;
		INSERT Tab_Teste VALUES (3,333) ;
	COMMIT; -- esse commando executa?
END $$
DELIMITER ;

CALL tratErroTransact();

SELECT * FROM Tab_Teste;